package javaswing;


import com.mysql.cj.x.protobuf.MysqlxCrud.Insert;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.awt.Button;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author LENOVO
 */
public class databaseplggn extends javax.swing.JFrame {
    
      String namaPelanggan = "";
    String alamatPelanggan = "";

        
    public databaseplggn() {
        initComponents();
        tabel();
        PLGNKONEKSI koneksi = new PLGNKONEKSI ();
        this.statuskoneksi.setText(koneksi.PLGNkoneksimysql2());;
        this.setLocationRelativeTo(this);
       

    }

    void reset() {
       
        nama.setText("");
        alamat.setText("");
        pencarian.setText("");
        
        
        ;
    }
    void cari() {
    DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("No.");
    tbl.addColumn("NAMA");
    tbl.addColumn("ALAMAT");

    try {
        String cari = pencarian.getText().trim();

        if (cari.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kolom pencarian kosong!");
            return;
        }

        String query = "SELECT * FROM datadiri WHERE nama LIKE ? OR alamat LIKE ?";
        Connection con = koneksii.getConnection();
        PreparedStatement pst = con.prepareStatement(query);

        // Set parameter pencarian
        pst.setString(1, "%" + cari + "%");
        pst.setString(2, "%" + cari + "%");

        ResultSet rs = pst.executeQuery();
        int no = 1;
        boolean found = false;

        while (rs.next()) {
            found = true;
            tbl.addRow(new Object[]{
                no++,
                rs.getString("NAMA"),
                rs.getString("ALAMAT")
            });
        }

        if (!found) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }

        tabel.setModel(tbl);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}



    public void tabel() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No.");
       
        tbl.addColumn("NAMA");
       
        tbl.addColumn("ALAMAT");

        try {
            int no = 1;
            Statement st = (Statement) koneksii.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM datadiri");

            while (rs.next()) {
                tbl.addRow(new Object[]{
                    no++,
                  
                    rs.getString("NAMA"),
                    
                    rs.getString("ALAMAT")
                });
                tabel.setModel(tbl);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        KIRIM = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pilih = new javax.swing.JComboBox<>();
        pencarian = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        statuskoneksi = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 234, 253));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(230, 230, 230));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PELANGGAN");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 530, 40));

        jLabel8.setFont(new java.awt.Font("Cooper Black", 0, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("WARUNG LEK HEN");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 330, 30));

        jLabel9.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Kedungwungu - Binangun - Blitar");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 390, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\resizecom_llogo_warung__1___1_-removebg-preview.png")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 150));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 160));

        jPanel7.setBackground(new java.awt.Color(230, 230, 230));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(188, 204, 220));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("PESAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 120, 40));

        delete.setBackground(new java.awt.Color(188, 204, 220));
        delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(102, 102, 102));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel7.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 40));

        RESET.setBackground(new java.awt.Color(188, 204, 220));
        RESET.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RESET.setForeground(new java.awt.Color(102, 102, 102));
        RESET.setText("RESET ");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        jPanel7.add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 120, 40));

        jButton3.setBackground(new java.awt.Color(188, 204, 220));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 40));

        KIRIM.setBackground(new java.awt.Color(188, 204, 220));
        KIRIM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        KIRIM.setForeground(new java.awt.Color(102, 102, 102));
        KIRIM.setText("INSERT");
        KIRIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KIRIMActionPerformed(evt);
            }
        });
        jPanel7.add(KIRIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 120, 40));

        EXIT.setBackground(new java.awt.Color(188, 204, 220));
        EXIT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EXIT.setForeground(new java.awt.Color(102, 102, 102));
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel7.add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 120, 40));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 970, 80));

        jPanel9.setBackground(new java.awt.Color(230, 230, 230));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(188, 204, 220));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Keterangan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Schadow BT", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAMA", "ALAMAT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabelMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tabel);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 480, 250));

        jPanel9.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 500, 310));

        jPanel5.setBackground(new java.awt.Color(188, 204, 220));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Input Data Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Schadow BT", 1, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel4.setText("NAMA");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 54, 113, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel5.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 50, 226, -1));

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        jPanel5.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 106, 226, -1));

        jLabel11.setFont(new java.awt.Font("Schadow BT", 1, 14)); // NOI18N
        jLabel11.setText("ALAMAT");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 110, 113, -1));

        jPanel9.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 390, 160));

        jPanel3.setBackground(new java.awt.Color(188, 204, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Input Data Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Schadow BT", 1, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        pilih.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAMA", "ALAMAT" }));
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });
        jPanel3.add(pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 23, 158, -1));
        jPanel3.add(pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 260, -1));

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jPanel9.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 390, 100));

        jPanel8.setBackground(new java.awt.Color(188, 204, 220));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Schadow BT", 1, 12)); // NOI18N
        jLabel3.setText("Status");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 26));

        statuskoneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statuskoneksiActionPerformed(evt);
            }
        });
        jPanel8.add(statuskoneksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 250, -1));

        jPanel9.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 390, 30));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 970, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int row = tabel.rowAtPoint(evt.getPoint());
       String nama1 = tabel.getValueAt(row, 1).toString();
         String alamat1 = tabel.getValueAt(row, 2).toString();
       
         nama.setText(nama1);
              alamat.setText(alamat1);
 
  
    }//GEN-LAST:event_tabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
            cari();
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed

    }//GEN-LAST:event_pilihActionPerformed

    private void statuskoneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statuskoneksiActionPerformed

    }//GEN-LAST:event_statuskoneksiActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            String data = "DELETE FROM datadiri WHERE nama ='" + nama.getText() + "'";
            Connection con = (Connection) koneksii.getConnection();
            PreparedStatement pst = con.prepareStatement(data);
            pst.execute();

            DefaultTableModel tblModel = (DefaultTableModel) tabel.getModel();

            if (tabel.getSelectedRowCount() == 1) {
                tblModel.removeRow(tabel.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Berhasil dihapus");
            } else {
                if (tabel.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "Tabel kosong!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Harap pilih satu data!!!");
                }
            }

            reset();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        if (nama.getText().isEmpty()
            || alamat.getText().isEmpty())
            
             {

            // Tampilkan pesan peringatan jika input belum lengkap
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua input sebelum mereset!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            // Panggil metode reset jika input sudah terisi
            reset();
        }
        
    }//GEN-LAST:event_RESETActionPerformed

    private void KIRIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KIRIMActionPerformed
      

        if (nama.getText().equals("") || alamat.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Data tidak lengkap!!!");

        } else {
            try {
                String data = "INSERT INTO datadiri VALUES ('" + nama.getText() + "','"
                
                + alamat.getText()
                + "')";
                Connection con = (Connection) koneksii.getConnection();
                PreparedStatement pst = con.prepareStatement(data);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Berhasil disimpan");

                reset();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal disimpan " + e.getMessage());
            }
        }
        tabel();
    }//GEN-LAST:event_KIRIMActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (nama.getText().equals("") || alamat.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Data tidak lengkap!!!");

        } else {

            try {
                String data = "UPDATE datadiri SET nama ='" + nama.getText()

                + "',alamat ='" + alamat.getText()
                + "'WHERE nama ='" + nama.getText() + "'";
                Connection con = (Connection) koneksii.getConnection();
                PreparedStatement pst = con.prepareStatement(data);
                pst.execute();

                DefaultTableModel tblModel = (DefaultTableModel) tabel.getModel();
                if (tabel.getSelectedRowCount() == 1) {

                    tblModel.setValueAt(nama.getText(), tabel.getSelectedRow(), 1);

                    tblModel.setValueAt(alamat.getText(), tabel.getSelectedRow(), 2);

                    JOptionPane.showMessageDialog(this, "Data berhasil diubah!!!");
                } else {
                    if (tabel.getRowCount() == 0) {
                        JOptionPane.showMessageDialog(this, "Tabel kosong!!!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Harap pilih satu data!!!");
                    }
                }

                reset();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (nama.getText().isEmpty() || alamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silakan pilih pelanggan terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            // Jika validasi lolos, lanjutkan ke dashboard
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin melanjutkan ke dashboard?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                dashboard Ds = new dashboard();
                Ds.setVisible(true);
                Ds.pack();
                this.dispose();
            }
        }
               
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       tabel();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databaseplggn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databaseplggn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databaseplggn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databaseplggn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databaseplggn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton KIRIM;
    private javax.swing.JButton RESET;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField pencarian;
    private javax.swing.JComboBox<String> pilih;
    private javax.swing.JTextField statuskoneksi;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
